" ****************************
" * configuration - PATHOGEN *
" ****************************
set encoding=utf-8
execute pathogen#infect()
syntax on
filetype plugin indent on

" ****************************
" * configuration - NERDTREE *
" ****************************

" Start NERDTree in every new tab
autocmd BufWinEnter * NERDTree

" Start NERDTree and leave the cursor in it.
autocmd VimEnter * NERDTree

" Start NERDTree and put the cursor back in the other window.
autocmd VimEnter * NERDTree | wincmd p

" Start NERDTree when Vim is started without file arguments.
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists('s:std_in') | NERDTree | endif

" Start NERDTree. If a file is specified, move the cursor to its window.
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * NERDTree | if argc() > 0 || exists("s:std_in") | wincmd p | endif

" Start NERDTree, unless a file or session is specified, eg. vim -S session_file.vim.
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists('s:std_in') && v:this_session == '' | NERDTree | endif

" Start NERDTree when Vim starts with a directory argument.
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists('s:std_in') |
    \ execute 'NERDTree' argv()[0] | wincmd p | enew | execute 'cd '.argv()[0] | endif

" Exit Vim if NERDTree is the only window remaining in the only tab.
com! -nargs=* -bar -bang -complete=dir  Lexplore  call netrw#Lexplore (<q-args>, <bang>0)

" Close the tab if NERDTree is the only window remaining in it.
autocmd BufEnter * if winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif

let NERDTreeShowHidden=1

"*******************************
"* configuration - VIM-AIRLINE *
"*******************************

set laststatus=2
set t_Co=256          
set noshowmode
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme='term'

" ************************
" * configuration - MISC *
" ************************

autocmd WinEnter * setlocal cursorline
autocmd WinEnter * setlocal signcolumn=auto

autocmd WinLeave * setlocal nocursorline
autocmd WinLeave * setlocal signcolumn=no

set directory=$HOME/.vim/vim_swap/ " put swap files to ~/.vim folder

" always save as sudo
cnoremap w!! w !sudo tee % > /dev/null  

set virtualedit+=all 	" allow virtualedit 
set backspace=2
set nocompatible
set number 						" show line numbers
set history=50
set ruler         		" show the cursor position all the time
set showcmd       		" display incomplete commands
set incsearch     		" do incremental searching
set laststatus=2  		" Always display the status line
set autowrite     		" Automatically :write before running commands
set modelines=0   		" Disable modelines as a security precaution
set nomodeline
set textwidth=80
set paste
set tabstop=2 
set softtabstop=2 
set shiftwidth=2 
set expandtab 
set shell=/bin/bash
